### ISSUE TITLE
관심상품 페이지 추가

### ISSUE THREAD

**Issue by haileypark-kr** [skkuse/2019spring_01class_team3#5]
관심상품 페이지 추가
- 관심 상품 리스트 모두 출력

**Comment by saanmin** [comment]
1. 관심상품 페이지 상에서 삭제버튼 미구현
ㄴ  view로 가서 삭제하고 favorite페이지 재로딩 해서 해결할 예정

2. 관심상품 페이지에서 링크로 해당 사이트로 이동하는 버튼 미구현
ㄴ pid의 url 긁어와서 하이퍼링크로 설정

**Comment by saanmin** [comment]
1, 2 해결
3. 로그인 여부 확인해서 
    ->로그인 되어 있으면 My Favorites ( view에서 uid 해당 유저로 바꿔서 ) 화면 이동하고 
    ->로그인 되어 있지 않으면, 로그인 하라는 창 띄운 뒤에 로그인 화면으로 이동함.

**Comment by haileypark-kr** [comment]
- 로그인 시 navbar에 관심상품 페이지 이동 버튼 추가
- 로그아웃 시 해당 url로 직접 접근 forbid하기
어떤가요?

**Comment by saanmin** [comment]
3. add_favorite, del_favorite 로그인 여부 확인해서
->로그인 되어 있으면 My Favorites ( view에서 uid 해당 유저로 바꿔서 ) 화면 이동하고
->로그인 되어 있지 않으면, 로그인 하라는 창 띄운 뒤에 로그인 화면으로 이동함.

4. add_favorite 하트 채우고 del_favorite 하트 비우고 :  ajax로 해결하기

5. Favorites에 상품 없을 때, height주기

**Comment by saanmin** [comment]
3,5 해결

**Comment by saanmin** [comment]
6. 하트 detail 화면 보여줄 때 부터 채우던지 비우던지 결정해서 띄우는 것. (4에서 업그레이드)

7. 같은 제품이면 한 카드로 작성하기

**Comment by saanmin** [comment]
4,6,7 해결
----------
